

name: dbt_day_ver1      # Projenin adı
version: '1.0'
config-version: 2

profile: default         # BigQuery profilin
target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

model-paths: ["models"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
seed-paths: ["seeds"]



