version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: Sales data from Greenweez
        columns:
          - name: date_date
            description: Purchase date
          - name: orders_id
            description: Order ID
          - name: product_id
            description: Product ID
        tests:
          - unique_combination_of_columns:
              combination_of_columns: ['orders_id', 'product_id']
      - name: product
        identifier: raw_gz_product
        description: Product information
        columns:
          - name: products_id
            description: Product ID
          - name: purchase_price
            description: Product purchase price
      - name: ship
        identifier: raw_gz_ship
        description: Shipping data
        columns:
          - name: orders_id
            description: Order ID
          - name: shipping_fee
            description: Shipping fee
          - name: shipping_fee_1
            description: Secondary shipping fee
          - name: logcost
            description: Logistical cost
          - name: ship_cost
            description: Final shipping cost

